"""newst update

Revision ID: 4695aeca9178
Revises: c9f3a1b27d6e
Create Date: 2026-10-09 15:53:01.698666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4695aeca9178'
down_revision: Union[str, None] = 'c9f3a1b27d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderIn')
    op.create_foreign_key(None, 'BayProfileItem', 'UserProfiles', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'BayProfileItem', type_='foreignkey')
    op.create_table('OrderIn',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('OrderIn_pkey'))
    )
    # ### end Alembic commands ###
