"""init

Revision ID: 9d45132aa6ae
Revises: b4d732aa6acb
Create Date: 2026-04-28 12:23:33.258448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d45132aa6ae'
down_revision: Union[str, None] = 'b4d732aa6acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderIn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderIn',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='OrderIn_pkey')
    )
    # ### end Alembic commands ###
